import "@/styles/globals.css";
import Header from "../components/Header";
import Head from "next/head";
import Script from "next/script";
import Footer from "@/components/Footer";
import { QueryClient, QueryClientProvider } from "react-query";

export default function App({ Component, pageProps }) {
  const queryClient = new QueryClient();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/daisyui@2.51.5/dist/full.css"
          rel="stylesheet"
          type="text/css"
        />
      </Head>
      <QueryClientProvider client={queryClient}>
        <Header />
        <Component {...pageProps} />
      </QueryClientProvider>
      <Footer />
    </>
  );
}
